# Generated by Django 5.1.4 on 2025-03-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('floor', models.CharField(choices=[('0', '*ALL'), ('1', 'KSL-1'), ('2', 'KSL-2'), ('3', 'KSL-3'), ('4', 'KSL-4'), ('5', 'KSL-5'), ('6', 'KSL-6'), ('7', 'KSL-7'), ('8', 'KSL-8'), ('9', 'KSL-9'), ('10', 'KSL-10'), ('11', 'KSL-11'), ('12', 'KSL-12'), ('13', 'KSL-13'), ('14', 'KSL-14'), ('15', 'KSL-15'), ('16', 'KSL-16'), ('17', 'KSL-17'), ('18', 'KSL-Sample'), ('19', 'FSL-1'), ('20', 'FSL-2'), ('21', 'FSL-3'), ('22', 'FSL-4'), ('23', 'FSL-5'), ('24', 'FSL-6'), ('25', 'FSL-Sample')], default='', max_length=2)),
                ('line', models.CharField(choices=[('0', '*ALL'), ('1', 'A'), ('2', 'A1'), ('3', 'A2'), ('4', 'B'), ('5', 'B1'), ('6', 'B2'), ('7', 'C'), ('8', 'C1'), ('9', 'C2'), ('10', 'D'), ('11', 'D1'), ('12', 'D2'), ('13', 'E'), ('14', 'E1'), ('16', 'E2'), ('17', 'F'), ('18', 'F1'), ('19', 'F2'), ('20', 'G'), ('21', 'H')], default='', max_length=2)),
                ('qc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('qc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=50)),
                ('product_type', models.CharField(blank=True, max_length=10, null=True)),
                ('total_inspect_quantity', models.IntegerField(blank=True, null=True)),
                ('fabric_fault', models.IntegerField(blank=True, default=0, null=True)),
                ('shading', models.IntegerField(blank=True, default=0, null=True)),
                ('trims_missing', models.IntegerField(blank=True, default=0, null=True)),
                ('bartack_missing', models.IntegerField(blank=True, default=0, null=True)),
                ('label_stitch_wrong_panel', models.IntegerField(blank=True, default=0, null=True)),
                ('others', models.IntegerField(blank=True, default=0, null=True)),
                ('broken', models.IntegerField(blank=True, default=0, null=True)),
                ('pleat', models.IntegerField(blank=True, default=0, null=True)),
                ('open_seam', models.IntegerField(blank=True, default=0, null=True)),
                ('damage', models.IntegerField(blank=True, default=0, null=True)),
                ('needle_mark', models.IntegerField(blank=True, default=0, null=True)),
                ('run_off_stitch', models.IntegerField(blank=True, default=0, null=True)),
                ('high_low', models.IntegerField(blank=True, default=0, null=True)),
                ('bad_tension', models.IntegerField(blank=True, default=0, null=True)),
                ('puckering', models.IntegerField(blank=True, default=0, null=True)),
                ('uneven', models.IntegerField(blank=True, default=0, null=True)),
                ('bias', models.IntegerField(blank=True, default=0, null=True)),
                ('skip', models.IntegerField(blank=True, default=0, null=True)),
                ('twisted', models.IntegerField(blank=True, default=0, null=True)),
                ('fabric_loose', models.IntegerField(blank=True, default=0, null=True)),
                ('fabric_catch', models.IntegerField(blank=True, default=0, null=True)),
                ('zipper_wavy', models.IntegerField(blank=True, default=0, null=True)),
                ('raw_edge', models.IntegerField(blank=True, default=0, null=True)),
                ('out_of_tolerance', models.IntegerField(blank=True, default=0, null=True)),
                ('oil', models.IntegerField(blank=True, default=0, null=True)),
                ('soilage', models.IntegerField(blank=True, default=0, null=True)),
                ('uncut_thread', models.IntegerField(blank=True, default=0, null=True)),
                ('number_mark', models.IntegerField(blank=True, default=0, null=True)),
                ('dirty_spot', models.IntegerField(blank=True, default=0, null=True)),
                ('color_bleed', models.IntegerField(blank=True, default=0, null=True)),
                ('others_defects', models.IntegerField(blank=True, default=0, null=True)),
                ('total_defect_points', models.IntegerField(blank=True, null=True)),
                ('dhu_shell_line', models.IntegerField(blank=True, null=True)),
                ('total_defect_pcs', models.IntegerField(blank=True, null=True)),
                ('defective_percentage', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
