# Generated by Django 5.1.4 on 2025-03-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectReport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectstatus',
            name='dhu_shell_line',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
