# Generated by Django 5.1.4 on 2025-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectReport_app', '0002_alter_defectstatus_dhu_shell_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectstatus',
            old_name='defective_percentage',
            new_name='defective_shell',
        ),
        migrations.AlterField(
            model_name='defectstatus',
            name='dhu_shell_line',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
