# Generated by Django 5.1.4 on 2025-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectReport_app', '0003_rename_defective_percentage_defectstatus_defective_shell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectstatus',
            old_name='damage',
            new_name='damage_1',
        ),
        migrations.RenameField(
            model_name='defectstatus',
            old_name='others',
            new_name='damage_2',
        ),
        migrations.AddField(
            model_name='defectstatus',
            name='others_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='defectstatus',
            name='others_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
