# Generated by Django 5.1.4 on 2025-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectReport_app', '0004_rename_damage_defectstatus_damage_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectstatus',
            name='defective_shell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
