# Generated by Django 5.1.4 on 2025-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectReport_app', '0005_alter_defectstatus_defective_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectstatus',
            name='buy_po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
