# Generated by Django 5.1.4 on 2025-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectReport_app', '0006_defectstatus_buy_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectstatus',
            name='order_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
